import "bootstrap/dist/css/bootstrap.css";
import "@/styles/globals.css";
import HeaderNavigation from "@/components/navigation/HeaderNavigation";
import Footer from "../components/Footer";
import { useCartContext } from "merchi_cart/src/CartProvider";

export const metadata = {
  title: "Silicone Wristbands | Easy Online Ordering, Free Shipping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { loadingTotals } = useCartContext();
  return (
    <html lang="en" className="h-100">
      <head></head>
      <body>
        <HeaderNavigation
          cartButtonWrappedInContainer={true}
          cartIconButtonClass=""
          currentUser={null}
          customSuccessMessage=""
          domainId={0}
          listContainerClass=""
          listItemClass=""
          showOpenCartButton={true}
          size=""
          storeId={0}
          cart={[]}
          setCart={() => {}}
          activeTabIndex={0}
          setActiveTabIndex={() => {}}
          alert={null}
          alertError={(message: string) => {}}
          alertSuccess={(message: string) => {}}
          setAlert={() => {}}
          cartItem={null}
          invoiceJson={null}
          setInvoiceJson={() => {}}
          cartSettingsInvalid={false}
          fetchingCart={true}
          setFetchingCart={() => {}}
          fetchingShipmentGroups={true}
          toggleCartModal={() => {}}
          updateCartShipmentAddress={() => {}}
          setCartItem={() => {}}
          tabs={[]}
          setTabs={() => {}}
          clearCart={() => {}}
          closeClearCart={() => {}}
          setCartComplete={() => {}}
          refetchCart={() => {}}
          loadingTotals={true}
          setLoadingTotals={() => {}}
          setActiveTabAndEditDisabled={() => {}}
          loading={true}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
